### ISSUE TITLE
Responses was changed

### ISSUE THREAD

**Issue by srphcr** [r7kamura/amazon-api-gateway-client#7]
AWS's response was changed.
So some of functions do not working.

``` node
TypeError: Cannot read property 'map' of undefined
    at NODE_PATH/lib/node_modules/fluct/node_modules/amazon-api-gateway-client/lib/client.js:303:25
    at runMicrotasksCallback (node.js:337:7)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by jtwebman** [comment]
This is a month old and not a word? IS @r7kamura not supporting this anymore? I am working on a fix now but this is my first time looking at this project.
